version: '3.9'

services:
  backend:
    container_name: post-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-post-backend
    ports:
      - 4000:3000
    env_file:
      - ./.env
    networks:
      - backend
  frontend:
    container_name: post-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-post-frontend
    ports:
      - 8080:80
    networks:
      - frontend
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/data/postgres
      -
  adminer:
    image: adminer
    ports:
      - 8081:8080
      -
volumes:
  postgres_data:

networks:
  backend:
  frontend:
